Repository DD2480G19/teammates, pull requests merged in 2023-02, with the labels that each got.

#15 Add new file for complexity answers
  .gitignore
  README.md
  complexity analysis.md
Labels: documentation

#27 doc: Add function 1 complexity calc. to README (#9)
  .gitignore
  README.md
Labels: documentation

#31 Doc: Add complexity calculation of function 4 (#12)
  README.md
Labels: documentation

#26 Doc: Add onboarding documentation to README
  .gitignore
  README.md
Labels: documentation

#28 Doc: Add complexity analysis of function 1 (#16)
  complexity analysis.md
Labels: documentation

#29 Doc: Add complexity analysis of function 2 (#17)
  complexity analysis.md
Labels: documentation

#47 Doc: Answers complexity-questions for function 9 (#24)
  complexity analysis.md
Labels: documentation

#48 Doc: Answer complexity-questions for function 10 (#25)
  complexity analysis.md
Labels: documentation

#58 Doc: Add doc for man. instr. of function 1
  README.md
Labels: documentation

#64 [#21] Answer complexity questions function 6
  README.md
Labels: documentation

#68 Doc: Add coverage-analysis to function 4 (#40)
  README.md
Labels: documentation

#66 [#20] Answer complexity questions function 5
  README.md
Labels: documentation

#69 Doc: Add documentation for coverage improvement of function 1
  README.md
  improved_coverage/function1/jacoco_report_new/html.zip
  improved_coverage/function1/jacoco_report_new/new_cov.png
  improved_coverage/function1/jacoco_report_new/new_coverage.md
  improved_coverage/function1/jacoco_report_old/html.zip
  improved_coverage/function1/jacoco_report_old/old_cov.png
  improved_coverage/function1/jacoco_report_old/old_coverage.md
Labels: documentation

#80 Doc: Add documentation for the refactoring of function 1
  README.md
Labels: documentation

#84 doc: Add documentation for coverage improvement of function 2 (#43)
  README.md
  improved_coverage_function_2/new_coverage.png
  improved_coverage_function_2/old_coverage.png
Labels: documentation

#83 doc: manual intrumentation code coverage function 2 (#38)
  README.md
Labels: documentation

#86 Feat: Coverage improvement function 4 (#45)
  FeedbackQuestionsLogicTest.out
  README.md
  build.gradle
  improved_coverage/function4/jacocoReport_new.zip
  improved_coverage/function4/jacocoReport_old.zip
  improved_coverage/function4/new_cov.png
  improved_coverage/function4/new_coverage.md
  improved_coverage/function4/old_cov.png
  improved_coverage/function4/old_coverage.md
  src/test/java/teammates/ui/webapi/GetSessionResultsActionTest.java
  src/test/resources/data/typicalDataBundle.json
Labels: documentation, enhancement

#90 Doc: Add evaluation for branch coverage by manual instrumentation fun…
  README.md
Labels: documentation

#94 Doc: Add refactoring plan for function 4 (#73)
  README.md
Labels: documentation

#98 Docs: Fix coverage improvement docs for function 4 (#97)
  README.md
  improved_coverage/function4/new_cov.png
  improved_coverage/function4/new_coverage.md
  improved_coverage/function4/old_cov.png
  improved_coverage/function4/old_coverage.md
Labels: bug, documentation

#105 Doc: Add an update for readme refactor function 5 reolves # 74
  README.md
Labels: documentation

#103 46 update readme coverage improvement function 5
  README.md
  improved_coverage/function5/new_jacoco_report/new_coverage.md
  improved_coverage/function5/new_jacoco_report/new_coverage.png
  improved_coverage/function5/old_jacoco_report/old_coverage.md
  improved_coverage/function5/old_jacoco_report/old_coverage.png
Labels: documentation

#115 Doc: Add P+ criteria to `README`
  README.md
Labels: documentation, enhancement

#117 Doc: Add short discussion about `Jacoco` in `README`
  README.md
Labels: documentation

#118 Doc: Remove `TODO`s from `README`
  README.md
Labels: documentation
